### ISSUE TITLE
What is wrong with the package?

### ISSUE THREAD

**Issue by agershun** [mathiasrw/node-red-contrib-alasql#2]

**Comment by mathiasrw** [comment]
Something in the configuration 

I started with a (very) simple plugin that did one thing (can't remember what) and replaced it with calling alasql

For some reason it made all of node not work so could not debug it. The last pull request fixed this but I have not if time to look at it again. 

It might be easier to start with a fresh and working plugin to restart the implementation - cause it SHOULD work - but have not us time to pin the fault.

**Comment by agershun** [comment]
Thank you for the answer. I will try to do it (I have seen your code - it seems OK). Hope, I will have time to do it )) BTW: AlaSQL can be the source for node-red-xls (in and out) nodes (I saw some request about such functionality).

**Comment by mathiasrw** [comment]
Sounds awesome. I have a strong feeling that xls ans xlsx is a very high demand feature. 

If you get it working, I will move it into the alasql group on github

**Comment by mathiasrw** [comment]
ps: a kind person came with some inputs on how to fix it: https://github.com/mathiasrw/node-red-contrib-alasql/issues/1#issuecomment-212596252

**Comment by agershun** [comment]
Probably, you missed the lines in `node-red-contrib-alasql.html` file. Now we have only one line:
```html
<script type="text/x-red" data-template-name="alasql"></script>
```
and it should be replaced with something like:
```html
<script type="text/x-red" data-template-name="alasql">
    <div class="form-row">
        <label for="node-input-name"><i class="icon-tag"></i> Name</label>
        <input type="text" id="node-input-name" placeholder="Name">
    </div>
</script>
```

**Comment by agershun** [comment]
@mathiasrw I sent the fixed files. Could you check them?
